### PR TITLE
Fix broken build that appeared last week

### LINKED ISSUE #7: Build breakage observed downstream
We observed the following in the SAW CI run:
```
COQC theories/Ref/EnTreeSpecFacts.v
File "./theories/Ref/EnTreeSpecFacts.v", line 432, characters 60-101:
Error: No such goal. The current bullet * is unfinished.

make[1]: *** [theories/Ref/EnTreeSpecFacts.vo] Error 1
```

Something must have changed upstream, as nothing changed here.

### PR DESCRIPTION
**Pull request by sauclovian-g**
Closes #7.

### CODE REVIEW

**Comment by Ptival** [comment]
I'm happy with the changes, it'd be nice if we understood what changed upstream, but if this helps unblock other tasks, please feel free to merge.

**Review by Ptival — APPROVED** [review]

**Comment by sauclovian-g** [comment]
I agree that it'd be nice to know but I think it's past the point of diminishing returns trying to find out. coq-ext-lib did change... but at the beginning of September and all of the changes in that version were administrative. So unless we were getting an even older coq-ext-lib until last week for some reason, I don't understand.

Anyway it's breaking the SAW CI so I'm going to go ahead and merge.

**Comment by RyanGlScott** [comment]
After some digging, I'm fairly certain that the relevant bit is that `entree-specs` successfully builds with `coq-paco-4.2.0` but not with `4.2.1`. (See [this comment](https://github.com/GaloisInc/entree-specs/issues/7#issuecomment-2416523063)). As such, I don't think our work here is done, as I believe the new code will now build with `4.2.1` but not with `4.2.0`. This is less bad since `opam` will likely pick `4.2.1` over `4.2.0` in most build plans, but there is nevertheless an issue still lying in wait.

@sauclovian-g, would you be willing to update this line in the `opam` file to indicate that `entree-specs` now requires building with `coq-paco-4.2.1` or later?

https://github.com/GaloisInc/entree-specs/blob/2ec3cab68797922dc2825bb6295dbdf6cfab9fbf/opam#L15

We should also update the "these bits no longer needed" comment accordingly.

**Comment by sauclovian-g** [comment]
Yup, I'll do that. (I apparently failed to notice before that the 4.1.2 constraint didn't actually say 4.2.1.)

**Comment by sauclovian-g** [comment]
Although on reflection I'll wait to push it until you merge #10, because it's going to conflict on the opam file and there's no point getting tangled.

**Pull request merged**
